"use client"

import {Inter} from "next/font/google";
import "./globals.css";
import {NavFull} from "@/components/NavFull";
import {Searchbar} from "@/components/Searchbar";
import {usePathname} from "next/navigation";
import {NavHalf} from "@/components/NavHalf";

const inter = Inter({subsets: ["latin"]});

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({children}) {

	const pathname = usePathname()

	return (
		<html lang="en">
		<body className={inter.className}>
		<div style={{display: "flex", flexDirection: "column"}}>
			{
				pathname === "/auth/login" || pathname === "/auth/signup" ?
					<>
						<NavHalf/>
					</> :
					<>
						<NavFull/>
						<Searchbar/>
					</>
			}
			<div style={{flex: 1}}>{children}</div>
		</div>
		</body>
		</html>
	);
}
